version: '3.1'

services:

    openvidu-js-screen-share-demo:
        image: openvidu/openvidu-js-screen-share-demo:2.25.0
        restart: on-failure
        environment:
            - OPENVIDU_URL=https://${DOMAIN_OR_PUBLIC_IP:-}:${HTTPS_PORT:-443}
            - OPENVIDU_SECRET=${OPENVIDU_SECRET:-}
            - OPENVIDU_APPLICATION_SERVER_URL=https://${DOMAIN_OR_PUBLIC_IP:-}:${HTTPS_PORT:-443}

    openvidu-js-demo:
        image: openvidu/openvidu-js-demo:2.25.0
        restart: on-failure
        environment:
            - OPENVIDU_URL=https://${DOMAIN_OR_PUBLIC_IP:-}:${HTTPS_PORT:-443}
            - OPENVIDU_SECRET=${OPENVIDU_SECRET:-}
            - OPENVIDU_APPLICATION_SERVER_URL=https://${DOMAIN_OR_PUBLIC_IP:-}:${HTTPS_PORT:-443}

    openvidu-roles-java-demo:
        image: openvidu/openvidu-roles-java-demo:2.25.0
        restart: on-failure
        environment:
            - OPENVIDU_URL=https://${DOMAIN_OR_PUBLIC_IP:-}:${HTTPS_PORT:-443}
            - OPENVIDU_SECRET=${OPENVIDU_SECRET:-}

    openvidu-classroom-demo:
        image: openvidu/openvidu-classroom-demo:2.25.0
        restart: on-failure
        environment:
            - OPENVIDU_URL=https://${DOMAIN_OR_PUBLIC_IP:-}:${HTTPS_PORT:-443}
            - OPENVIDU_SECRET=${OPENVIDU_SECRET:-}

    openvidu-getaroom-demo:
        image: openvidu/openvidu-getaroom-demo:2.25.0
        restart: on-failure
        environment:
            - OPENVIDU_URL=https://${DOMAIN_OR_PUBLIC_IP:-}:${HTTPS_PORT:-443}
            - OPENVIDU_SECRET=${OPENVIDU_SECRET:-}
            - OPENVIDU_APPLICATION_SERVER_URL=https://${DOMAIN_OR_PUBLIC_IP:-}:${HTTPS_PORT:-443}

    openvidu-call:
        image: openvidu/openvidu-call:2.25.0-demos
        restart: on-failure
        environment:
            - OPENVIDU_URL=https://${DOMAIN_OR_PUBLIC_IP:-}:${HTTPS_PORT:-443}
            - OPENVIDU_SECRET=${OPENVIDU_SECRET:-}
            - CALL_OPENVIDU_CERTTYPE=${CERTIFICATE_TYPE}
            - CALL_PRIVATE_ACCESS=${CALL_PRIVATE_ACCESS:-DISABLED}
            - CALL_USER=${CALL_USER:-}
            - CALL_SECRET=${CALL_SECRET:-}
            - CALL_ADMIN_SECRET=${CALL_ADMIN_SECRET:-}
            - CALL_RECORDING=${CALL_RECORDING:-}

    openvidu-basic-node-demo:
        image: openvidu/openvidu-basic-node-demo:2.25.0
        restart: on-failure
        environment:
            - OPENVIDU_URL=https://${DOMAIN_OR_PUBLIC_IP:-}:${HTTPS_PORT:-443}
            - OPENVIDU_SECRET=${OPENVIDU_SECRET:-}

    demos-page:
        image: openvidu/openvidu-demo-proxy:2.25.0
        restart: on-failure
        ports:
            - "5442:80"
        environment:
            - URL_OV_JS_DEMO=http://openvidu-js-demo:5000
            - URL_OV_JS_SCREENSHARE_DEMO=http://openvidu-js-screen-share-demo:5000
            - URL_OV_ROLES_JAVA_DEMO=https://openvidu-roles-java-demo:5000
            - URL_OV_CLASSROOM_DEMO=https://openvidu-classroom-demo:5000
            - URL_OV_GETAROOM_DEMO=http://openvidu-getaroom-demo:5000
            - URL_OV_CALL=http://openvidu-call:5000
            - URL_APPLICATION_SERVER=http://openvidu-basic-node-demo:5000
            - REDIRECT_INDEX_TO_DOMAIN=${REDIRECT_INDEX_TO_DOMAIN:-}
